# Generated by Django 3.2.8 on 2023-05-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['usuario'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='contacto',
            name='contraseña',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, verbose_name='Usuario'),
        ),
    ]
