# Generated by Django 3.2.8 on 2023-05-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_auto_20230513_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nuevousuario',
            options={'ordering': ['usuario'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='nuevousuario',
            name='contraseña',
            field=models.CharField(blank=True, max_length=150, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='nuevousuario',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, verbose_name='Usuario'),
        ),
    ]
