# Generated by Django 3.2.8 on 2023-05-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0004_auto_20230513_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='comunidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comunidades', models.CharField(max_length=50)),
                ('tipo_comunidades', models.CharField(max_length=50)),
                ('direccion_comunidades', models.CharField(max_length=50)),
                ('conserje_nombre', models.CharField(max_length=50)),
                ('fono_comunidades', models.IntegerField()),
                ('n_unidades', models.IntegerField()),
                ('n_residentes', models.IntegerField()),
            ],
            options={
                'db_table': 'comunidades',
            },
        ),
    ]
