# Generated by Django 3.2.8 on 2023-05-30 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0005_comunidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='id_propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name': 'propietario',
                'verbose_name_plural': 'propietarios',
                'db_table': 'id_propietarios',
            },
        ),
        migrations.CreateModel(
            name='id_residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residente', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name': 'residente',
                'verbose_name_plural': 'residentes',
                'db_table': 'id_residentes',
            },
        ),
        migrations.AlterModelOptions(
            name='comunidades',
            options={'verbose_name': 'Comunidad', 'verbose_name_plural': 'Comunidades'},
        ),
        migrations.AlterField(
            model_name='comunidades',
            name='tipo_comunidades',
            field=models.CharField(choices=[('Condominio', 'Condiminio'), ('Edificio', 'Edificio'), ('Loteo', 'Loteo'), ('Villa', 'Villa')], default='Condominio', max_length=20),
        ),
        migrations.CreateModel(
            name='unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_recinto', models.CharField(max_length=50, verbose_name='unidad')),
                ('tipo_unidad', models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento')], default='Casa', max_length=13)),
                ('direccion_unidad', models.CharField(max_length=50)),
                ('nombre_villa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombre_villa', to='contacto.comunidades')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'db_table': 'unidades',
            },
        ),
        migrations.CreateModel(
            name='residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('telefono_residente', models.IntegerField()),
                ('n_recinto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n_recinto_residente', to='contacto.unidades')),
                ('rut_propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietarioID', to='contacto.id_propietario')),
                ('rut_residente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residentesID', to='contacto.id_residente')),
                ('tipo_unidad_residente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombre_unidad', to='contacto.unidades')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
                'db_table': 'residentes',
            },
        ),
        migrations.CreateModel(
            name='propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('telefono_propetario', models.IntegerField()),
                ('estado', models.CharField(max_length=10)),
                ('n_recinto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n_recinto_propietario', to='contacto.unidades')),
                ('rut_propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rut_propietario', to='contacto.id_propietario')),
                ('rut_residente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rut_residente', to='contacto.id_residente')),
                ('tipo_unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_unidad_propietario', to='contacto.unidades')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'db_table': 'propietarios',
            },
        ),
    ]
