# Generated by Django 3.2.8 on 2023-05-30 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0007_auto_20230529_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comununidad', to='contacto.comunidades'),
        ),
        migrations.AddField(
            model_name='unidades',
            name='propetario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propetario', to='contacto.id_propietario'),
        ),
        migrations.AddField(
            model_name='unidades',
            name='telefono_propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefono_propetario', to='contacto.id_propietario'),
        ),
    ]
