# Generated by Django 3.2.8 on 2023-06-01 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0008_auto_20230529_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidades',
            name='propetario',
        ),
        migrations.AddField(
            model_name='unidades',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario_id', to='contacto.id_propietario'),
        ),
    ]
