# Generated by Django 3.2.8 on 2023-06-01 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0009_auto_20230531_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propietario',
            old_name='telefono_propetario',
            new_name='telefono_propietario',
        ),
    ]
