# Generated by Django 3.2.8 on 2023-06-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0011_alter_unidades_telefono_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='telefono_propietario',
            field=models.IntegerField(verbose_name='telefono_propietario'),
        ),
    ]
