# Generated by Django 3.2.8 on 2023-06-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0013_alter_propietario_telefono_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='telefono_propietario',
            field=models.IntegerField(),
        ),
    ]
