# Generated by Django 3.2.8 on 2023-06-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0016_alter_comunidades_tipo_comunidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='tipo_unidad',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='residente',
            name='tipo_unidad_residente',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
