# Generated by Django 3.2.8 on 2023-06-13 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0018_auto_20230613_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Id_conserje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name': 'id_conserje',
                'verbose_name_plural': 'id_conserje',
                'db_table': 'id_conserje',
            },
        ),
        migrations.CreateModel(
            name='estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_estacionamiento', models.CharField(max_length=5)),
                ('n_recinto_estacionamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n_recinto_estacionamiento', to='contacto.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Conserje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=50)),
                ('fono_conserje', models.IntegerField()),
                ('comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidad', to='contacto.comunidades')),
                ('rut_conserje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rut_conserje', to='contacto.id_conserje')),
            ],
        ),
        migrations.CreateModel(
            name='bodegas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_bodega', models.CharField(max_length=5)),
                ('n_recinto_bodegas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n_recinto_bodegas', to='contacto.unidades')),
            ],
        ),
    ]
