# Generated by Django 3.2.8 on 2023-06-14 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0019_bodegas_conserje_estacionamiento_id_conserje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodegas',
            options={'verbose_name': 'Bodega', 'verbose_name_plural': 'Bodegas'},
        ),
        migrations.AlterModelOptions(
            name='conserje',
            options={'verbose_name': 'Conserje', 'verbose_name_plural': 'Conserjes'},
        ),
        migrations.AlterModelOptions(
            name='estacionamiento',
            options={'verbose_name': 'Estacionamiento', 'verbose_name_plural': 'Estacionamientos'},
        ),
        migrations.AlterModelTable(
            name='bodegas',
            table='bodegas',
        ),
        migrations.AlterModelTable(
            name='conserje',
            table='conserjes',
        ),
        migrations.AlterModelTable(
            name='estacionamiento',
            table='estacionamientos',
        ),
    ]
