# Generated by Django 3.2.8 on 2023-06-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0020_auto_20230613_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conserje',
            name='rut_conserje',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
