# Generated by Django 3.2.8 on 2023-06-14 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0021_alter_conserje_rut_conserje'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodegas',
            name='comunidad_bodegas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidad_bodegas', to='contacto.comunidades'),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='comunidad_estacionamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidad_estacionamiento', to='contacto.comunidades'),
        ),
    ]
