# Generated by Django 3.2.8 on 2023-06-14 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0022_auto_20230614_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='n_recinto_estacionamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n_recinto_estacionamiento', to='contacto.unidades'),
        ),
    ]
