# Generated by Django 3.2.8 on 2023-06-19 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0023_alter_estacionamiento_n_recinto_estacionamiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='propietario',
        ),
    ]
