# Generated by Django 3.2.8 on 2023-06-19 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0024_delete_propietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_unidad', models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento')], max_length=15, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono_propietario', models.IntegerField()),
                ('estado', models.CharField(max_length=10)),
                ('n_recinto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n_recinto_propietario', to='contacto.unidades')),
                ('rut_propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rut_propietario', to='contacto.id_propietario')),
                ('rut_residente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rut_residente', to='contacto.id_residente')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'db_table': 'propietarios',
            },
        ),
    ]
