# Generated by Django 3.2.8 on 2023-06-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0025_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='residente',
            name='estado_r',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10, null=True),
        ),
    ]
