# Generated by Django 3.2.8 on 2023-06-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0026_auto_20230620_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='telefono_propietario',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
