# Generated by Django 3.2.8 on 2023-06-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0027_alter_unidades_telefono_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='grupo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
