# Generated by Django 3.2.8 on 2023-07-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0028_unidades_grupo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Id_conserje',
        ),
    ]
