# Generated by Django 3.2.8 on 2023-07-05 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0029_delete_id_conserje'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActasE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actasE', models.CharField(max_length=5)),
                ('asuntoE', models.CharField(max_length=20)),
                ('descripcionE', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'actaE',
                'verbose_name_plural': 'actasE',
                'db_table': 'actasE',
            },
        ),
        migrations.CreateModel(
            name='ActasO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actasO', models.CharField(max_length=5, null=True)),
                ('asunto', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'actaO',
                'verbose_name_plural': 'actasO',
                'db_table': 'actasO',
            },
        ),
        migrations.CreateModel(
            name='ResidentesT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_unidad_residenteT', models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento')], max_length=15, null=True)),
                ('direccionT', models.CharField(max_length=50)),
                ('telefono_residentTe', models.IntegerField()),
                ('estado_rT', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('n_recintoT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n_recinto_residenteT', to='contacto.unidades')),
                ('rut_propietarioT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietariotID', to='contacto.id_propietario')),
                ('rut_residenteT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residentestID', to='contacto.id_residente')),
            ],
            options={
                'verbose_name': 'ResidenteT',
                'verbose_name_plural': 'ResidentesT',
                'db_table': 'residentesT',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_proveedores', models.CharField(max_length=10, null=True)),
                ('nombre_proveedor', models.CharField(max_length=50, null=True)),
                ('comunidad_proveedores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidad_proveedores', to='contacto.comunidades')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Medidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_medidor', models.IntegerField()),
                ('tipo_medidor', models.CharField(choices=[('Luz', 'Luz'), ('Agua', 'Agua')], max_length=10)),
                ('comunidad_medidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidad_medidor', to='contacto.comunidades')),
            ],
            options={
                'verbose_name': 'Medidor',
                'verbose_name_plural': 'Medidores',
                'db_table': 'medidores',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bitacora', models.CharField(max_length=5)),
                ('nombre_bitacora', models.CharField(max_length=20)),
                ('comunidad_bitacora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidad_bitacora', to='contacto.comunidades')),
            ],
            options={
                'verbose_name': 'bitacora',
                'verbose_name_plural': 'bitacoras',
                'db_table': 'bitacoras',
            },
        ),
    ]
