tipos=(
    ('Condominio','Condiminio'),
    ('Edificio','Edificio'),
    ('Loteo','Loteo'),
    ('Villa','Villa')
)
tiposU=(
    ('Casa','Casa'),
    ('Departamento','Departamento'),
)
estados=(
    ('Activo','Activo'),
    ('Inactivo','Inactivo'),
)